apiVersion: v1
kind: Namespace
metadata:
  name: sales-system
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-data
  namespace: sales-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: sales-system
spec:
  selector:
    matchLabels:
      app: database
  replicas: 1
  template:
    metadata:
      labels:
        app: database
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: database-data
      containers:
        - name: postgres
          image: postgres:15.3
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data
          resources:
            requests:
              cpu: "500m"
              memory: 500Mi
            limits:
              cpu: "500m"
              memory: 500Mi
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
              name: postgres
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - localhost
                - -U
                - postgres
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - localhost
                - -U
                - postgres
            initialDelaySeconds: 5
            timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: sales-system
spec:
  type: ClusterIP
  selector:
    app: database
  ports:
    - port: 5432
      name: postgres
      targetPort: postgres