apiVersion: v1
kind: Namespace
metadata:
  name: sales-system

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales
  namespace: sales-system
spec:
  selector:
    matchLabels:
      app: sales
  template:
    metadata:
      labels:
        app: sales
    spec:
      containers:
      - name: sales-api
        image: service-image
        ports:
          - name: sales-api
            containerPort: 3000
          - name: sales-api-debug
            containerPort: 4000
        env:
          - name: GOMAXPROCS
            valueFrom:
              resourceFieldRef:
                resource: limits.cpu
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: KUBERNETES_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: KUBERNETES_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KUBERNETES_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        readinessProbe:
          httpGet:
            port: 4000
            path: /debug/readiness
          initialDelaySeconds: 2
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        livenessProbe:
          httpGet:
            port: 4000
            path: /debug/liveness
          initialDelaySeconds: 2
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2

---

apiVersion: v1
kind: Service
metadata:
  name: sales-api
  namespace: sales-system

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sales-debug-api
  namespace: sales-system
spec:
  ingressClassName: nginx
  rules:
    - host: sales-debug-api.iron1.debotjes.nl
      http:
        paths:
          - backend:
              service:
                name: sales-api
                port:
                  number: 4000
            path: /
            pathType: Prefix

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sales-api
  namespace: sales-system
spec:
  ingressClassName: nginx
  rules:
    - host: sales-api.iron1.debotjes.nl
      http:
        paths:
          - backend:
              service:
                name: sales-api
                port:
                  number: 3000
            path: /
            pathType: Prefix
